### ISSUE TITLE
How to remove timers in version 1.1.0?

### ISSUE THREAD

**Issue by WestSide56** [KashCherry/Timer-Fix-plugin#10]
I would like to see a lesson on how to delete timers in the new version. In the transition from 1.0.8 to 1.1.0 were removed timers with different indetification.

**Comment by aaamouii** [comment]
There are no special changes in the identification of timers in these verisons. The main identification problem was in version 1.0.9 (which is why it was removed). However, in version 1.1.0, new timers use timer identifiers that have already been deleted. Maybe I misunderstand you?

**Comment by WestSide56** [comment]
I use timers on this principle:
SetTimerEx("PlayerOneSecond", 1000, false, "d", playerid);

public PlayerOneSecond(playerid)
{
    if(!IsPlayerConnected(playerid)) return 1;
    //functions
    return SetTimerEx("PlayerOneSecond", 1000, false, "d", playerid);
}

In addition, many other timers are used.
The timers are re-created inside.
On version 1.0.8 everything works flawlessly.

**Comment by WestSide56** [comment]
In some places the KillTimer function is used, maybe the wrong identifier is deleted? Timer indicator - variable (new val = SetTimerEx...)

**Comment by WestSide56** [comment]
The fix will be? I noticed that version 1.0.8 has a size twice larger than 1.1.0 and this is good as the plugin consumes a lot of server resources.

**Comment by WestSide56** [comment]
The problem is relevant in version 1.1.1

After some time, the timers stop working on their own

**Comment by aaamouii** [comment]
Check the latest version, please. I hope it's fixed now.
