### ISSUE TITLE
sampctl compatibility 

### ISSUE THREAD

**Issue by deejcoder** [KashCherry/Timer-Fix-plugin#11]
Release for latest release needs to be renamed to a .zip, or for pawn.json to be updated
`WARN: failed to ensure package github.com/KashCherry/Timer-Fix-plugin: failed to ensure asset: failed to get plugin KashCherry/Timer-Fix-plugin from net: resource matcher '^timerfix-(.+)-win32.zip$' does not match any release assets from '[ timerfix-1.1.0-linux.tar.gz timerfix-1.1.0-win32.rar]'`

**Comment by aaamouii** [comment]
Should be fixed now.
