### ISSUE TITLE
SetCustomTimerEx: bad parameter count

### ISSUE THREAD

**Issue by Dragon-Knight** [KashCherry/Timer-Fix-plugin#14]
native SetCustomTimerEx(funcname[], delay, count, const format[], {Float,_}:...);

SetCustomTimerEx("Player_OnPlayerConnectEx", 2500, 1, "d", player_id);

[timerfix.plugin] n_SetCustomTimerEx: bad parameter count (count is 5, should be greater than 6)

**Comment by Pedrilkov** [comment]
The author is mocking, his plugin cannot be used

**Comment by aaamouii** [comment]
Check the latest release, please. I hope it's fixed now.
