### ISSUE TITLE
Support for sampctl

### ISSUE THREAD

**Issue by dhpancor** [KashCherry/Timer-Fix-plugin#3]
Hello!

This plugin is great! However, a lot of users uses sampctl.

Could you add compatibility with it?

Thanks :D

**Comment by aaamouii** [comment]
Compatibility with sampctl has been added.

**Comment by NikHalif** [comment]
sampctl warn:
WARN: failed to ensure plugin github.com/KashCherry/Timer-Fix-plugin failed to get plugin github.com/KashCherry/Timer-Fix-plugin from net: resource matcher '^timerfix-(.+)-windows.zip$' does not match any release assets from '[ timerfix-1.0.8-linux.tar.gz timerfix-1.0.8-win32.zip]'
Please edit pawn.json
