### ISSUE TITLE
SetTimerEx: unknown format specifer

### ISSUE THREAD

**Issue by YECHEZ** [KashCherry/Timer-Fix-plugin#4]
Hello, thanks for the great plugin.
How can I get more information about the warning [timerfix.plugin] SetTimerEx: unknown format specifer ?
All ex-timers that I use have attributes "d", "i" and "id" (this work on default sa-mp timers).

upd. It seems it was possible to solve, but it is necessary to test better
I had several timers with the "id" parameters. It seems because of this and there was a warning

**Comment by aaamouii** [comment]
Hi, thanks for your report.

Can you give me an example of how you use it?

I did some tests and found no problem.

**Comment by YECHEZ** [comment]
Resolved. The warning was in one of the includes, where the timer was with the parameter "x".
