### ISSUE TITLE
error: cannot execute callback with name "Malloc_SolidifyTimer"

### ISSUE THREAD

**Issue by ghost** [KashCherry/Timer-Fix-plugin#5]
[plugin.timerfix] error: cannot execute callback with name "Malloc_SolidifyTimer"
[plugin.timerfix] error: cannot execute callback with name "Malloc_SolidifyTimer"

**Comment by aaamouii** [comment]
What plugins and includes do you use?
How often does this error occur?
Code?

**Comment by Y-Less** [comment]
So you know, this is the calling code:

https://github.com/pawn-lang/YSI-Includes/blob/c2fe718f0f52383a20b0d40f1150903048913c89/YSI_Coding/y_malloc/heapalloc.inc#L159-L160

**Comment by aaamouii** [comment]
Timer Fix works fine with this interval, check out the latest release.
