### ISSUE TITLE
Timer id`s limit needed to remove.

### ISSUE THREAD

**Issue by Fleynaro** [KashCherry/Timer-Fix-plugin#7]
Timer id`s limit needed to remove. Or how to change delay of a timer while it process? I need a public that would be a local environment where there are its local variables I can change.

For example:
new timer; //need to remove the limit 0xFFFF
public myTimer(a, Float: b)
{
new delay = 200 + (a % 2) ? 100 : 300;
timer = SetTimerEx("myTimer", delay, false, "if", a + 1, b + 5.0); //local vars a and b are changed by such way(not necessary to declare global vars)
return 1;
}

If anything, there are a lot of such timers in my gamemode. Average delay = 200 ms. Therefore to declare a global array with those vars is not the best way in my opinion.

**Comment by aaamouii** [comment]
You can use SetTimerInterval.
And I already removed limit.

**Comment by Fleynaro** [comment]
Sorry, but:
if (currentId >= 0xFFFF) {
		delete remoteTimer;
		CConsole::Get()->Log("limit reached");
		return INVALID_TIMER_ID;
	}

I tried your latest release and the limit remains(linux)

**Comment by Fleynaro** [comment]
SetTimerInterval is good, but what about using local vars without global ones?

**Comment by Fleynaro** [comment]
Do not close please this topic while the issue will not be resolved.

**Comment by Fleynaro** [comment]
KillTimer needed to use in that case? 

For example:
new timer; //need to remove the limit 0xFFFF
public myTimer(a, Float: b)
{
new delay = 200 + (a % 2) ? 100 : 300;
KillTimer(timer);
timer = SetTimerEx("myTimer", delay, false, "if", a + 1, b + 5.0); //local vars a and b are changed by such way(not necessary to declare global vars)
return 1;
}

**Comment by aaamouii** [comment]
Yes. Release will be later.

**Comment by Fleynaro** [comment]
Ok, I wait for this)

**Comment by aaamouii** [comment]
Limit removed. Release updated.

**Comment by Fleynaro** [comment]
> Limit removed. Release updated.

Where can I donwload this release? I see only releases updated up to 18 november.
Thanks)

**Comment by aaamouii** [comment]
Just download 1.0.7 version again.

**Comment by Fleynaro** [comment]
https://github.com/KashCherry/Timer-Fix-plugin/releases/tag/v1.0.7 Here the plugin file has been updated for the last time 18 november. Thus not any changes done. Or what I understood wrong?

**Comment by aaamouii** [comment]
Just download it.

**Comment by Fleynaro** [comment]
Ok, the limit is removed. I hope if even the limit reach 0xFFFFFFFF timers will not stop. Thanks)
