### ISSUE TITLE
sampctl error

### ISSUE THREAD

**Issue by NikHalif** [KashCherry/Timer-Fix-plugin#8]
sampctl warn:
WARN: failed to ensure plugin github.com/KashCherry/Timer-Fix-plugin failed to get plugin github.com/KashCherry/Timer-Fix-plugin from net: resource matcher '^timerfix-(.+)-windows.zip$' does not match any release assets from '[ timerfix-1.0.8-linux.tar.gz timerfix-1.0.8-win32.zip]'
Please edit pawn.json

**Comment by aaamouii** [comment]
Updated.
